AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30

Resources:
  AppFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub power-user-${AWS::StackName}-lambda
      PermissionsBoundary: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/PermissionBoundary_PowerUser
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lambda-basic-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.lambda_handler
      CodeUri: .
      Role: !GetAtt AppFunctionExecutionRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

Outputs:
  AppUrl:
    Description: Public Lambda Function URL
    Value: !GetAtt AppFunctionUrl.FunctionUrl
  HealthCheckUrl:
    Description: Public health-check URL
    Value: !Sub '${AppFunctionUrl.FunctionUrl}health'
